### ISSUE TITLE
Incorrect internal calls?

### ISSUE THREAD

**Issue by PG-TUe** [openml/python#18]
The Task entity calls the get_pandas function of the Dataset entity (in function get_X_and_Y), which does not exist (probably should be get_dataset).
Specifically, calling code underneath got me the error
````
    from openml.apiconnector import APIConnector
    connector = APIConnector(apikey = 'key')
    task = connector.download_task(59)
    x1,y1,x2,y2 = task.get_train_and_test_set()
````

**Comment by joaquinvanschoren** [comment]
Thanks. What was the error, exactly?

**Comment by PG-TUe** [comment]
My bad, I thought I included it, is underlying traceback sufficient?
````
Traceback (most recent call last):
  File "...\TaskScript.py", line 5, in <module>
    dataset = task.get_train_and_test_set()
  File "...\openml\entities\task.py", line 67, in get_train_and_test_set
    X, Y = self.get_X_and_Y()
  File "...\openml\entities\task.py", line 47, in get_X_and_Y
    X_and_Y = dataset.get_pandas(target=self.target_feature)
AttributeError: 'OpenMLDataset' object has no attribute 'get_pandas'
````

**Comment by PG-TUe** [comment]
Closed since it has been fixed (see [this issue](https://github.com/openml/python/issues/19))
